from enum import Enum


class UserRole(str, Enum):
    ADMIN = "admin"
    PATIENT = "patient"
    DOCTOR = "doctor"
    HOSPITAL_ADMIN = "hospital_admin"
    INSURER_ADMIN = "insurer_admin"
    CLAIM_PROCESSOR = "claim_processor"


class ClaimStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FLAGGED_FRAUD = "FLAGGED_FRAUD"
    PARTIALLY_APPROVED = "PARTIALLY_APPROVED"


class ClaimType(str, Enum):
    INPATIENT = "INPATIENT"
    OUTPATIENT = "OUTPATIENT"
    EMERGENCY = "EMERGENCY"
    PHARMACY = "PHARMACY"
    DENTAL = "DENTAL"
    VISION = "VISION"


class DocumentType(str, Enum):
    INVOICE = "INVOICE"
    PRESCRIPTION = "PRESCRIPTION"
    INSURANCE_CARD = "INSURANCE_CARD"
    MEDICAL_REPORT = "MEDICAL_REPORT"
    POLICY_DOCUMENT = "POLICY_DOCUMENT"


class PolicyType(str, Enum):
    INDIVIDUAL_HEALTH = "INDIVIDUAL_HEALTH"
    FAMILY_FLOATER = "FAMILY_FLOATER"
    CRITICAL_ILLNESS = "CRITICAL_ILLNESS"
    GROUP_HEALTH = "GROUP_HEALTH"
    TOP_UP = "TOP_UP"
